apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: openvelox
spec:
  project: default
  source:
    chart: flink-kubernetes-operator
    repoURL: https://downloads.apache.org/flink/flink-kubernetes-operator-1.14.0/
    targetRevision: 1.14.0
  destination:
    server: https://kubernetes.default.svc
    namespace: streaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
