apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches-oauth2-proxy.yaml
  - path: patches-tfl-producer-strimzi.yaml
  - path: patches-flink-session.yaml
