apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: batch
  annotations:
    iam.gke.io/gcp-service-account: airflow-sa@openvelox-dev-01.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: batch
  annotations:
    iam.gke.io/gcp-service-account: spark-sa@openvelox-dev-01.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: streaming
  annotations:
    iam.gke.io/gcp-service-account: flink-sa@openvelox-dev-01.iam.gserviceaccount.com
