#!/usr/bin/env bash
#
# Renders every *.tmpl.yaml in the repo to its sibling *.yaml, substituting
# ONLY the variables declared in config.env.  Any other ${...} sequences in
# the template (for example ${ENV:TRINO_OAUTH_CLIENT_SECRET} or runtime-pod
# ${PROJECT_ID} placeholders) are left untouched.
#
# Usage:
#   scripts/render-manifests.sh            # render everything
#   scripts/render-manifests.sh --check    # exit 1 if any rendered file is stale
#
# Fork workflow:
#   1. Edit config.env
#   2. Run scripts/render-manifests.sh
#   3. git add -A && git commit -m "Reconfigure for fork"

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${REPO_ROOT}/config.env"
CHECK_ONLY="false"

if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY="true"
fi

if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "ERROR: ${CONFIG_FILE} not found.  Copy config.env.example and edit it." >&2
  exit 1
fi

# Load config.env into this shell (no secrets allowed in that file).
set -a
# shellcheck disable=SC1090
source "${CONFIG_FILE}"
set +a

# The exhaustive list of variables we substitute.  Keep this in sync with
# config.env.  Any variable NOT in this list is preserved verbatim in the
# rendered output even if it happens to be exported.
ALLOWED_VARS=(DOMAIN GITHUB_ORG GITHUB_REPO)

# Validate each required variable is non-empty.
for var in "${ALLOWED_VARS[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "ERROR: ${var} is unset or empty in ${CONFIG_FILE}" >&2
    exit 1
  fi
done

# Build the envsubst whitelist expression: '${DOMAIN} ${GITHUB_ORG} ...'
ENVSUBST_VARS=""
for var in "${ALLOWED_VARS[@]}"; do
  ENVSUBST_VARS+="\${${var}} "
done

if ! command -v envsubst >/dev/null 2>&1; then
  echo "ERROR: envsubst not found.  Install gettext (macOS: brew install gettext)." >&2
  exit 1
fi

HEADER_MARKER="# DO NOT EDIT — generated by scripts/render-manifests.sh from"

stale=0
rendered=0

while IFS= read -r -d '' tmpl; do
  target="${tmpl%.tmpl.yaml}.yaml"
  rel_tmpl="${tmpl#${REPO_ROOT}/}"
  rel_target="${target#${REPO_ROOT}/}"

  # Render into a temp file, then compare/move.
  tmp_out="$(mktemp)"
  {
    printf '%s %s\n' "${HEADER_MARKER}" "${rel_tmpl}"
    printf '# Source of truth: edit the .tmpl.yaml then run scripts/render-manifests.sh\n'
    envsubst "${ENVSUBST_VARS}" < "${tmpl}"
  } > "${tmp_out}"

  if [[ "${CHECK_ONLY}" == "true" ]]; then
    if [[ ! -f "${target}" ]] || ! diff -q "${tmp_out}" "${target}" >/dev/null 2>&1; then
      echo "STALE: ${rel_target}"
      stale=$((stale + 1))
    fi
    rm -f "${tmp_out}"
  else
    if [[ -f "${target}" ]] && diff -q "${tmp_out}" "${target}" >/dev/null 2>&1; then
      rm -f "${tmp_out}"
    else
      mv "${tmp_out}" "${target}"
      echo "rendered  ${rel_target}"
      rendered=$((rendered + 1))
    fi
  fi
done < <(find "${REPO_ROOT}" \
  -type d \( -name node_modules -o -name .terraform -o -name .venv -o -name venv -o -name .git -o -name .claude \) -prune -o \
  -type f -name '*.tmpl.yaml' -print0)

if [[ "${CHECK_ONLY}" == "true" ]]; then
  if (( stale > 0 )); then
    echo "" >&2
    echo "${stale} file(s) are stale.  Run scripts/render-manifests.sh and commit." >&2
    exit 1
  fi
  echo "All rendered files are up to date."
else
  echo ""
  echo "Done. ${rendered} file(s) regenerated."
fi
