apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: openvelox
spec:
  project: default
  sources:
    - chart: kafka-ui
      repoURL: https://kafbat.github.io/helm-charts
      targetRevision: 1.5.0
      helm:
        valueFiles:
          - $values/helm/kafka-ui/values-gke.yaml
    - repoURL: https://github.com/${GITHUB_ORG}/${GITHUB_REPO}.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
