apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: platform
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    spec:
      containers:
        - name: keycloak
          env:
            - name: KC_HOSTNAME
              value: "https://dev.auth.${DOMAIN}"
            - name: KC_HOSTNAME_ADMIN
              value: "https://dev.auth.${DOMAIN}"
