apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: openvelox
spec:
  project: default
  sources:
    - chart: airflow
      repoURL: https://airflow.apache.org
      targetRevision: 1.20.0
      helm:
        valueFiles:
          - $values/helm/airflow/values-gke.yaml
          - $values/helm/airflow/values-prod.yaml
    - repoURL: https://github.com/${GITHUB_ORG}/${GITHUB_REPO}.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: batch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
